export default {
  CONTAINER_WIDTH: '90%',
  SPACE_BETWEEN_EACH_STACK_ITEM: 4,

  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_TITLE: 22,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',

  STANDART_BUTTON_SIZE: 'lg',
  STANDART_BUTTON_BACKGROUND_COLOR: '#0891B2',
};
